### ISSUE TITLE
Rework Coward specialist

### ISSUE THREAD

**Issue by mike-eason** [mike-eason/solaris#541]
- Needs to be cheaper
- Or have a better buff

Suggested by Trapdoorspyder

**Comment by belongkl-baesys** [comment]
It could flee with a percentage of its ships if it will lose the battle, I believe it would incentivize riskier attacks. 

Because we wouldn't want the fleeing ships to be calculated towards damaging the defenders it would require running the battle calculations twice, once with all attacking ships (determining the Coward lost) and then again after removing the fleeing ships from the count.

**Comment by mike-eason** [comment]
Resolved in upcoming update.
